### ISSUE TITLE
No data in data folder csv files

### ISSUE THREAD

**Issue by vashist1994** [agrawal-rohit/stackoverflow-semantic-search#3]
Hey i would like to take your attention on the data folder in your github, there is no data in any of the csv files there

**Comment by agrawal-rohit** [comment]
Does it happen even after cloning the repo? You may not be able to download the data directly from Github because it's linked by Git LFS

**Comment by vashist1994** [comment]
even after cloning the data is not available

**Comment by agrawal-rohit** [comment]
Sorry for the late reply, here's the data: https://drive.google.com/drive/folders/14tjD8SoYLhmb3t90-1pPiTueOxZKo-qX?usp=sharing
