### ISSUE TITLE
Unable to download Original_data.csv (This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.)

### ISSUE THREAD

**Issue by galactica1983** [agrawal-rohit/stackoverflow-semantic-search#4]
Hi, I'm not able to download the "Original_data.csv", could you help to check it?
Thanks!

> git clone https://github.com/agrawal-rohit/stackoverflow-semantic-search.git
Cloning into 'stackoverflow-semantic-search'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 148 (delta 9), reused 12 (delta 2), pack-reused 115
Receiving objects: 100% (148/148), 190.03 MiB | 2.22 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Updating files: 100% (65/65), done.
Downloading data/Original_data.csv (1.1 GB)
Error downloading object: data/Original_data.csv (71b8759): Smudge error: Error downloading data/Original_data.csv (71b87592420d14d538342076c37bd6c5629d86b419dbecaec08b1f097217d6d1): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by naruto-1998** [comment]
yeah me too faced the same porblem but afterwards i just downloaded the stackover flow(public dataset)  using google bigquery API with filtering only the required columns as mentioned in the code given

**Comment by agrawal-rohit** [comment]
Sorry for the late reply, here's the data: https://drive.google.com/drive/folders/14tjD8SoYLhmb3t90-1pPiTueOxZKo-qX?usp=sharing
